/* engine.c generated by valac 0.16.0, the Vala compiler
 * generated from engine.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gdk/gdk.h>


#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_TYPE_BASE (org_westhoffswelt_pdfpresenter_renderer_cache_base_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_TYPE_BASE, orgwesthoffsweltpdfpresenterRendererCacheBase))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_TYPE_BASE, orgwesthoffsweltpdfpresenterRendererCacheBaseClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_IS_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_IS_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_TYPE_BASE, orgwesthoffsweltpdfpresenterRendererCacheBaseClass))

typedef struct _orgwesthoffsweltpdfpresenterRendererCacheBase orgwesthoffsweltpdfpresenterRendererCacheBase;
typedef struct _orgwesthoffsweltpdfpresenterRendererCacheBaseClass orgwesthoffsweltpdfpresenterRendererCacheBaseClass;
typedef struct _orgwesthoffsweltpdfpresenterRendererCacheBasePrivate orgwesthoffsweltpdfpresenterRendererCacheBasePrivate;

#define ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_TYPE_BASE (org_westhoffswelt_pdfpresenter_metadata_base_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_TYPE_BASE, orgwesthoffsweltpdfpresenterMetadataBase))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_TYPE_BASE, orgwesthoffsweltpdfpresenterMetadataBaseClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_IS_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_IS_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_METADATA_TYPE_BASE, orgwesthoffsweltpdfpresenterMetadataBaseClass))

typedef struct _orgwesthoffsweltpdfpresenterMetadataBase orgwesthoffsweltpdfpresenterMetadataBase;
typedef struct _orgwesthoffsweltpdfpresenterMetadataBaseClass orgwesthoffsweltpdfpresenterMetadataBaseClass;

#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_TYPE_ENGINE (org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_TYPE_ENGINE, orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_TYPE_ENGINE, orgwesthoffsweltpdfpresenterRendererCacheSimpleEngineClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_IS_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_TYPE_ENGINE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_IS_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_TYPE_ENGINE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_ENGINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_TYPE_ENGINE, orgwesthoffsweltpdfpresenterRendererCacheSimpleEngineClass))

typedef struct _orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine;
typedef struct _orgwesthoffsweltpdfpresenterRendererCacheSimpleEngineClass orgwesthoffsweltpdfpresenterRendererCacheSimpleEngineClass;
typedef struct _orgwesthoffsweltpdfpresenterRendererCacheSimpleEnginePrivate orgwesthoffsweltpdfpresenterRendererCacheSimpleEnginePrivate;
#define _g_mutex_free0(var) ((var == NULL) ? NULL : (var = (g_mutex_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _orgwesthoffsweltpdfpresenterRendererCacheBase {
	GObject parent_instance;
	orgwesthoffsweltpdfpresenterRendererCacheBasePrivate * priv;
	orgwesthoffsweltpdfpresenterMetadataBase* metadata;
};

struct _orgwesthoffsweltpdfpresenterRendererCacheBaseClass {
	GObjectClass parent_class;
	void (*store) (orgwesthoffsweltpdfpresenterRendererCacheBase* self, guint index, GdkPixmap* pixmap);
	GdkPixmap* (*retrieve) (orgwesthoffsweltpdfpresenterRendererCacheBase* self, guint index);
};

struct _orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine {
	orgwesthoffsweltpdfpresenterRendererCacheBase parent_instance;
	orgwesthoffsweltpdfpresenterRendererCacheSimpleEnginePrivate * priv;
	GdkPixmap** storage;
	gint storage_length1;
	GMutex* mutex;
};

struct _orgwesthoffsweltpdfpresenterRendererCacheSimpleEngineClass {
	orgwesthoffsweltpdfpresenterRendererCacheBaseClass parent_class;
};


static gpointer org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_parent_class = NULL;

GType org_westhoffswelt_pdfpresenter_renderer_cache_base_get_type (void) G_GNUC_CONST;
GType org_westhoffswelt_pdfpresenter_metadata_base_get_type (void) G_GNUC_CONST;
GType org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_get_type (void) G_GNUC_CONST;
enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_ENGINE_DUMMY_PROPERTY
};
orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine* org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_new (orgwesthoffsweltpdfpresenterMetadataBase* metadata);
orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine* org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_construct (GType object_type, orgwesthoffsweltpdfpresenterMetadataBase* metadata);
orgwesthoffsweltpdfpresenterRendererCacheBase* org_westhoffswelt_pdfpresenter_renderer_cache_base_construct (GType object_type, orgwesthoffsweltpdfpresenterMetadataBase* metadata);
guint org_westhoffswelt_pdfpresenter_metadata_base_get_slide_count (orgwesthoffsweltpdfpresenterMetadataBase* self);
static void org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_real_store (orgwesthoffsweltpdfpresenterRendererCacheBase* base, guint index, GdkPixmap* pixmap);
static GdkPixmap* org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_real_retrieve (orgwesthoffsweltpdfpresenterRendererCacheBase* base, guint index);
static void org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


/**
         * Initialize the cache store
         */
orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine* org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_construct (GType object_type, orgwesthoffsweltpdfpresenterMetadataBase* metadata) {
	orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine * self = NULL;
	orgwesthoffsweltpdfpresenterMetadataBase* _tmp0_;
	GMutex* _tmp1_;
	orgwesthoffsweltpdfpresenterMetadataBase* _tmp2_;
	guint _tmp3_ = 0U;
	GdkPixmap** _tmp4_ = NULL;
	GMutex* _tmp5_;
	g_return_val_if_fail (metadata != NULL, NULL);
	_tmp0_ = metadata;
	self = (orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine*) org_westhoffswelt_pdfpresenter_renderer_cache_base_construct (object_type, _tmp0_);
	_tmp1_ = self->mutex;
	g_mutex_lock (_tmp1_);
	_tmp2_ = ((orgwesthoffsweltpdfpresenterRendererCacheBase*) self)->metadata;
	_tmp3_ = org_westhoffswelt_pdfpresenter_metadata_base_get_slide_count (_tmp2_);
	_tmp4_ = g_new0 (GdkPixmap*, _tmp3_ + 1);
	self->storage = (_vala_array_free (self->storage, self->storage_length1, (GDestroyNotify) g_object_unref), NULL);
	self->storage = _tmp4_;
	self->storage_length1 = _tmp3_;
	_tmp5_ = self->mutex;
	g_mutex_unlock (_tmp5_);
	return self;
}


orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine* org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_new (orgwesthoffsweltpdfpresenterMetadataBase* metadata) {
	return org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_construct (ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_TYPE_ENGINE, metadata);
}


/**
         * Store a pixmap in the cache using the given index as identifier
         */
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_real_store (orgwesthoffsweltpdfpresenterRendererCacheBase* base, guint index, GdkPixmap* pixmap) {
	orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine * self;
	GMutex* _tmp0_;
	GdkPixmap** _tmp1_;
	gint _tmp1__length1;
	guint _tmp2_;
	GdkPixmap* _tmp3_;
	GdkPixmap* _tmp4_;
	GdkPixmap* _tmp5_;
	GMutex* _tmp6_;
	self = (orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine*) base;
	g_return_if_fail (pixmap != NULL);
	_tmp0_ = self->mutex;
	g_mutex_lock (_tmp0_);
	_tmp1_ = self->storage;
	_tmp1__length1 = self->storage_length1;
	_tmp2_ = index;
	_tmp3_ = pixmap;
	_tmp4_ = _g_object_ref0 (_tmp3_);
	_g_object_unref0 (_tmp1_[_tmp2_]);
	_tmp1_[_tmp2_] = _tmp4_;
	_tmp5_ = _tmp1_[_tmp2_];
	_tmp6_ = self->mutex;
	g_mutex_unlock (_tmp6_);
}


/**
         * Retrieve a stored pixmap from the cache.
         *
         * If no item with the given index is available null is returned
         */
static GdkPixmap* org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_real_retrieve (orgwesthoffsweltpdfpresenterRendererCacheBase* base, guint index) {
	orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine * self;
	GdkPixmap* result = NULL;
	GdkPixmap** _tmp0_;
	gint _tmp0__length1;
	guint _tmp1_;
	GdkPixmap* _tmp2_;
	GdkPixmap* _tmp3_;
	self = (orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine*) base;
	_tmp0_ = self->storage;
	_tmp0__length1 = self->storage_length1;
	_tmp1_ = index;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


static void org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_class_init (orgwesthoffsweltpdfpresenterRendererCacheSimpleEngineClass * klass) {
	org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_parent_class = g_type_class_peek_parent (klass);
	ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_BASE_CLASS (klass)->store = org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_real_store;
	ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_BASE_CLASS (klass)->retrieve = org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_real_retrieve;
	G_OBJECT_CLASS (klass)->finalize = org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_finalize;
}


static void org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_instance_init (orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine * self) {
	GMutex* _tmp0_;
	self->storage = NULL;
	_tmp0_ = g_mutex_new ();
	self->mutex = _tmp0_;
}


static void org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_finalize (GObject* obj) {
	orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine * self;
	self = ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_SIMPLE_ENGINE (obj);
	self->storage = (_vala_array_free (self->storage, self->storage_length1, (GDestroyNotify) g_object_unref), NULL);
	_g_mutex_free0 (self->mutex);
	G_OBJECT_CLASS (org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_parent_class)->finalize (obj);
}


/**
     * Cache store which simply holds all given items in memory.
     */
GType org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_get_type (void) {
	static volatile gsize org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_type_id__volatile = 0;
	if (g_once_init_enter (&org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (orgwesthoffsweltpdfpresenterRendererCacheSimpleEngineClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine), 0, (GInstanceInitFunc) org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_instance_init, NULL };
		GType org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_type_id;
		org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_type_id = g_type_register_static (ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_CACHE_TYPE_BASE, "orgwesthoffsweltpdfpresenterRendererCacheSimpleEngine", &g_define_type_info, 0);
		g_once_init_leave (&org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_type_id__volatile, org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_type_id);
	}
	return org_westhoffswelt_pdfpresenter_renderer_cache_simple_engine_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



