/* timer_label.c generated by valac 0.16.0, the Vala compiler
 * generated from timer_label.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <time.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>


#define ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_TIMER_LABEL (org_westhoffswelt_pdfpresenter_timer_label_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_TIMER_LABEL, orgwesthoffsweltpdfpresenterTimerLabel))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_TIMER_LABEL, orgwesthoffsweltpdfpresenterTimerLabelClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_IS_TIMER_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_TIMER_LABEL))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_IS_TIMER_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_TIMER_LABEL))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_TIMER_LABEL, orgwesthoffsweltpdfpresenterTimerLabelClass))

typedef struct _orgwesthoffsweltpdfpresenterTimerLabel orgwesthoffsweltpdfpresenterTimerLabel;
typedef struct _orgwesthoffsweltpdfpresenterTimerLabelClass orgwesthoffsweltpdfpresenterTimerLabelClass;

#define ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTDOWN_TIMER (org_westhoffswelt_pdfpresenter_countdown_timer_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTDOWN_TIMER, orgwesthoffsweltpdfpresenterCountdownTimer))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTDOWN_TIMER, orgwesthoffsweltpdfpresenterCountdownTimerClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_IS_COUNTDOWN_TIMER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTDOWN_TIMER))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_IS_COUNTDOWN_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTDOWN_TIMER))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTDOWN_TIMER, orgwesthoffsweltpdfpresenterCountdownTimerClass))

typedef struct _orgwesthoffsweltpdfpresenterCountdownTimer orgwesthoffsweltpdfpresenterCountdownTimer;
typedef struct _orgwesthoffsweltpdfpresenterCountdownTimerClass orgwesthoffsweltpdfpresenterCountdownTimerClass;

#define ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_END_TIME_TIMER (org_westhoffswelt_pdfpresenter_end_time_timer_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_END_TIME_TIMER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_END_TIME_TIMER, orgwesthoffsweltpdfpresenterEndTimeTimer))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_END_TIME_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_END_TIME_TIMER, orgwesthoffsweltpdfpresenterEndTimeTimerClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_IS_END_TIME_TIMER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_END_TIME_TIMER))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_IS_END_TIME_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_END_TIME_TIMER))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_END_TIME_TIMER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_END_TIME_TIMER, orgwesthoffsweltpdfpresenterEndTimeTimerClass))

typedef struct _orgwesthoffsweltpdfpresenterEndTimeTimer orgwesthoffsweltpdfpresenterEndTimeTimer;
typedef struct _orgwesthoffsweltpdfpresenterEndTimeTimerClass orgwesthoffsweltpdfpresenterEndTimeTimerClass;

#define ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTUP_TIMER (org_westhoffswelt_pdfpresenter_countup_timer_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTUP_TIMER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTUP_TIMER, orgwesthoffsweltpdfpresenterCountupTimer))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTUP_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTUP_TIMER, orgwesthoffsweltpdfpresenterCountupTimerClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_IS_COUNTUP_TIMER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTUP_TIMER))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_IS_COUNTUP_TIMER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTUP_TIMER))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTUP_TIMER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTUP_TIMER, orgwesthoffsweltpdfpresenterCountupTimerClass))

typedef struct _orgwesthoffsweltpdfpresenterCountupTimer orgwesthoffsweltpdfpresenterCountupTimer;
typedef struct _orgwesthoffsweltpdfpresenterCountupTimerClass orgwesthoffsweltpdfpresenterCountupTimerClass;
typedef struct _orgwesthoffsweltpdfpresenterTimerLabelPrivate orgwesthoffsweltpdfpresenterTimerLabelPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _orgwesthoffsweltpdfpresenterCountdownTimerPrivate orgwesthoffsweltpdfpresenterCountdownTimerPrivate;
typedef struct _orgwesthoffsweltpdfpresenterEndTimeTimerPrivate orgwesthoffsweltpdfpresenterEndTimeTimerPrivate;
typedef struct _orgwesthoffsweltpdfpresenterCountupTimerPrivate orgwesthoffsweltpdfpresenterCountupTimerPrivate;

struct _orgwesthoffsweltpdfpresenterTimerLabel {
	GtkLabel parent_instance;
	orgwesthoffsweltpdfpresenterTimerLabelPrivate * priv;
	gint time;
	time_t start_time;
	guint timeout;
	GdkColor normal_color;
	GdkColor pretalk_color;
};

struct _orgwesthoffsweltpdfpresenterTimerLabelClass {
	GtkLabelClass parent_class;
	void (*start) (orgwesthoffsweltpdfpresenterTimerLabel* self);
	void (*stop) (orgwesthoffsweltpdfpresenterTimerLabel* self);
	void (*reset) (orgwesthoffsweltpdfpresenterTimerLabel* self);
	gboolean (*on_timeout) (orgwesthoffsweltpdfpresenterTimerLabel* self);
	void (*format_time) (orgwesthoffsweltpdfpresenterTimerLabel* self);
};

struct _orgwesthoffsweltpdfpresenterCountdownTimer {
	orgwesthoffsweltpdfpresenterTimerLabel parent_instance;
	orgwesthoffsweltpdfpresenterCountdownTimerPrivate * priv;
	gint duration;
	guint last_minutes;
	GdkColor last_minutes_color;
	GdkColor negative_color;
};

struct _orgwesthoffsweltpdfpresenterCountdownTimerClass {
	orgwesthoffsweltpdfpresenterTimerLabelClass parent_class;
};

struct _orgwesthoffsweltpdfpresenterEndTimeTimer {
	orgwesthoffsweltpdfpresenterCountdownTimer parent_instance;
	orgwesthoffsweltpdfpresenterEndTimeTimerPrivate * priv;
	time_t end_time;
	struct tm end_time_object;
};

struct _orgwesthoffsweltpdfpresenterEndTimeTimerClass {
	orgwesthoffsweltpdfpresenterCountdownTimerClass parent_class;
};

struct _orgwesthoffsweltpdfpresenterCountupTimer {
	orgwesthoffsweltpdfpresenterTimerLabel parent_instance;
	orgwesthoffsweltpdfpresenterCountupTimerPrivate * priv;
};

struct _orgwesthoffsweltpdfpresenterCountupTimerClass {
	orgwesthoffsweltpdfpresenterTimerLabelClass parent_class;
};


static gpointer org_westhoffswelt_pdfpresenter_timer_label_parent_class = NULL;
static gpointer org_westhoffswelt_pdfpresenter_countdown_timer_parent_class = NULL;
static gpointer org_westhoffswelt_pdfpresenter_end_time_timer_parent_class = NULL;
static gpointer org_westhoffswelt_pdfpresenter_countup_timer_parent_class = NULL;

GType org_westhoffswelt_pdfpresenter_timer_label_get_type (void) G_GNUC_CONST;
orgwesthoffsweltpdfpresenterTimerLabel* org_westhoffswelt_pdfpresenter_getTimerLabel (gint duration, time_t end_time, guint last_minutes, time_t start_time);
orgwesthoffsweltpdfpresenterEndTimeTimer* org_westhoffswelt_pdfpresenter_end_time_timer_new (time_t end_time, guint last_minutes, time_t start_time);
orgwesthoffsweltpdfpresenterEndTimeTimer* org_westhoffswelt_pdfpresenter_end_time_timer_construct (GType object_type, time_t end_time, guint last_minutes, time_t start_time);
GType org_westhoffswelt_pdfpresenter_countdown_timer_get_type (void) G_GNUC_CONST;
GType org_westhoffswelt_pdfpresenter_end_time_timer_get_type (void) G_GNUC_CONST;
orgwesthoffsweltpdfpresenterCountdownTimer* org_westhoffswelt_pdfpresenter_countdown_timer_new (gint duration, guint last_minutes, time_t start_time);
orgwesthoffsweltpdfpresenterCountdownTimer* org_westhoffswelt_pdfpresenter_countdown_timer_construct (GType object_type, gint duration, guint last_minutes, time_t start_time);
orgwesthoffsweltpdfpresenterCountupTimer* org_westhoffswelt_pdfpresenter_countup_timer_new (time_t start_time);
orgwesthoffsweltpdfpresenterCountupTimer* org_westhoffswelt_pdfpresenter_countup_timer_construct (GType object_type, time_t start_time);
GType org_westhoffswelt_pdfpresenter_countup_timer_get_type (void) G_GNUC_CONST;
enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_DUMMY_PROPERTY
};
orgwesthoffsweltpdfpresenterTimerLabel* org_westhoffswelt_pdfpresenter_timer_label_construct (GType object_type, time_t start_time);
void org_westhoffswelt_pdfpresenter_timer_label_start (orgwesthoffsweltpdfpresenterTimerLabel* self);
static void org_westhoffswelt_pdfpresenter_timer_label_real_start (orgwesthoffsweltpdfpresenterTimerLabel* self);
gboolean org_westhoffswelt_pdfpresenter_timer_label_on_timeout (orgwesthoffsweltpdfpresenterTimerLabel* self);
static gboolean _org_westhoffswelt_pdfpresenter_timer_label_on_timeout_gsource_func (gpointer self);
void org_westhoffswelt_pdfpresenter_timer_label_stop (orgwesthoffsweltpdfpresenterTimerLabel* self);
static void org_westhoffswelt_pdfpresenter_timer_label_real_stop (orgwesthoffsweltpdfpresenterTimerLabel* self);
gboolean org_westhoffswelt_pdfpresenter_timer_label_pause (orgwesthoffsweltpdfpresenterTimerLabel* self);
void org_westhoffswelt_pdfpresenter_timer_label_reset (orgwesthoffsweltpdfpresenterTimerLabel* self);
static void org_westhoffswelt_pdfpresenter_timer_label_real_reset (orgwesthoffsweltpdfpresenterTimerLabel* self);
gint org_westhoffswelt_pdfpresenter_timer_label_calculate_countdown (orgwesthoffsweltpdfpresenterTimerLabel* self);
void org_westhoffswelt_pdfpresenter_timer_label_format_time (orgwesthoffsweltpdfpresenterTimerLabel* self);
static gboolean org_westhoffswelt_pdfpresenter_timer_label_real_on_timeout (orgwesthoffsweltpdfpresenterTimerLabel* self);
static void org_westhoffswelt_pdfpresenter_timer_label_real_format_time (orgwesthoffsweltpdfpresenterTimerLabel* self);
void org_westhoffswelt_pdfpresenter_timer_label_show_time (orgwesthoffsweltpdfpresenterTimerLabel* self, guint timeInSecs, const gchar* prefix);
static void org_westhoffswelt_pdfpresenter_timer_label_finalize (GObject* obj);
enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER_DUMMY_PROPERTY
};
static void org_westhoffswelt_pdfpresenter_countdown_timer_real_format_time (orgwesthoffsweltpdfpresenterTimerLabel* base);
static void org_westhoffswelt_pdfpresenter_countdown_timer_finalize (GObject* obj);
enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_END_TIME_TIMER_DUMMY_PROPERTY
};
static void org_westhoffswelt_pdfpresenter_end_time_timer_real_start (orgwesthoffsweltpdfpresenterTimerLabel* base);
static void org_westhoffswelt_pdfpresenter_end_time_timer_real_stop (orgwesthoffsweltpdfpresenterTimerLabel* base);
static void org_westhoffswelt_pdfpresenter_end_time_timer_real_reset (orgwesthoffsweltpdfpresenterTimerLabel* base);
static gboolean org_westhoffswelt_pdfpresenter_end_time_timer_real_on_timeout (orgwesthoffsweltpdfpresenterTimerLabel* base);
static void org_westhoffswelt_pdfpresenter_end_time_timer_finalize (GObject* obj);
enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTUP_TIMER_DUMMY_PROPERTY
};
static void org_westhoffswelt_pdfpresenter_countup_timer_real_format_time (orgwesthoffsweltpdfpresenterTimerLabel* base);


/**
      * Factory function for creating TimerLabels, depending if a duration was
      * given.
      */
orgwesthoffsweltpdfpresenterTimerLabel* org_westhoffswelt_pdfpresenter_getTimerLabel (gint duration, time_t end_time, guint last_minutes, time_t start_time) {
	orgwesthoffsweltpdfpresenterTimerLabel* result = NULL;
	time_t _tmp0_;
	_tmp0_ = end_time;
	if (_tmp0_ > ((time_t) 0)) {
		time_t _tmp1_;
		guint _tmp2_;
		time_t _tmp3_;
		orgwesthoffsweltpdfpresenterEndTimeTimer* _tmp4_;
		orgwesthoffsweltpdfpresenterTimerLabel* _tmp5_;
		_tmp1_ = end_time;
		_tmp2_ = last_minutes;
		_tmp3_ = start_time;
		_tmp4_ = org_westhoffswelt_pdfpresenter_end_time_timer_new (_tmp1_, _tmp2_, _tmp3_);
		_tmp5_ = (orgwesthoffsweltpdfpresenterTimerLabel*) g_object_ref_sink (_tmp4_);
		result = _tmp5_;
		return result;
	} else {
		gint _tmp6_;
		_tmp6_ = duration;
		if (_tmp6_ > 0) {
			gint _tmp7_;
			guint _tmp8_;
			time_t _tmp9_;
			orgwesthoffsweltpdfpresenterCountdownTimer* _tmp10_;
			orgwesthoffsweltpdfpresenterTimerLabel* _tmp11_;
			_tmp7_ = duration;
			_tmp8_ = last_minutes;
			_tmp9_ = start_time;
			_tmp10_ = org_westhoffswelt_pdfpresenter_countdown_timer_new (_tmp7_, _tmp8_, _tmp9_);
			_tmp11_ = (orgwesthoffsweltpdfpresenterTimerLabel*) g_object_ref_sink (_tmp10_);
			result = _tmp11_;
			return result;
		} else {
			time_t _tmp12_;
			orgwesthoffsweltpdfpresenterCountupTimer* _tmp13_;
			orgwesthoffsweltpdfpresenterTimerLabel* _tmp14_;
			_tmp12_ = start_time;
			_tmp13_ = org_westhoffswelt_pdfpresenter_countup_timer_new (_tmp12_);
			_tmp14_ = (orgwesthoffsweltpdfpresenterTimerLabel*) g_object_ref_sink (_tmp13_);
			result = _tmp14_;
			return result;
		}
	}
}


/**
         * Default constructor taking the initial time as argument, as well as
         * the time to countdown until the talk actually starts.
         *
         * The second argument is optional. If no countdown_time is specified
         * the countdown will be disabled. The timer is paused in such a case
         * at the given intial_time.
         */
orgwesthoffsweltpdfpresenterTimerLabel* org_westhoffswelt_pdfpresenter_timer_label_construct (GType object_type, time_t start_time) {
	orgwesthoffsweltpdfpresenterTimerLabel * self = NULL;
	time_t _tmp0_;
	GdkColor _tmp1_ = {0};
	GdkColor _tmp2_ = {0};
	self = (orgwesthoffsweltpdfpresenterTimerLabel*) g_object_new (object_type, NULL);
	_tmp0_ = start_time;
	self->start_time = _tmp0_;
	gdk_color_parse ("white", &_tmp1_);
	self->normal_color = _tmp1_;
	gdk_color_parse ("green", &_tmp2_);
	self->pretalk_color = _tmp2_;
	return self;
}


/**
         * Start the timer
         */
static gboolean _org_westhoffswelt_pdfpresenter_timer_label_on_timeout_gsource_func (gpointer self) {
	gboolean result;
	result = org_westhoffswelt_pdfpresenter_timer_label_on_timeout (self);
	return result;
}


static void org_westhoffswelt_pdfpresenter_timer_label_real_start (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	gboolean _tmp0_ = FALSE;
	guint _tmp1_;
	gboolean _tmp3_;
	_tmp1_ = self->timeout;
	if (_tmp1_ != ((guint) 0)) {
		gint _tmp2_;
		_tmp2_ = self->time;
		_tmp0_ = _tmp2_ < 0;
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		self->time = 0;
	} else {
		guint _tmp4_;
		_tmp4_ = self->timeout;
		if (_tmp4_ == ((guint) 0)) {
			guint _tmp5_ = 0U;
			_tmp5_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, _org_westhoffswelt_pdfpresenter_timer_label_on_timeout_gsource_func, g_object_ref (self), g_object_unref);
			self->timeout = _tmp5_;
		}
	}
}


void org_westhoffswelt_pdfpresenter_timer_label_start (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	g_return_if_fail (self != NULL);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_GET_CLASS (self)->start (self);
}


/**
         * Stop the timer
         */
static void org_westhoffswelt_pdfpresenter_timer_label_real_stop (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	guint _tmp0_;
	_tmp0_ = self->timeout;
	if (_tmp0_ != ((guint) 0)) {
		guint _tmp1_;
		_tmp1_ = self->timeout;
		g_source_remove (_tmp1_);
		self->timeout = (guint) 0;
	}
}


void org_westhoffswelt_pdfpresenter_timer_label_stop (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	g_return_if_fail (self != NULL);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_GET_CLASS (self)->stop (self);
}


/**
         * Pauses the timer if it's running. Returns if the timer is paused.
         */
gboolean org_westhoffswelt_pdfpresenter_timer_label_pause (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	gboolean result = FALSE;
	gboolean paused;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	paused = FALSE;
	_tmp0_ = self->time;
	if (_tmp0_ > 0) {
		guint _tmp1_;
		_tmp1_ = self->timeout;
		if (_tmp1_ != ((guint) 0)) {
			org_westhoffswelt_pdfpresenter_timer_label_stop (self);
			paused = TRUE;
		} else {
			org_westhoffswelt_pdfpresenter_timer_label_start (self);
		}
	}
	result = paused;
	return result;
}


/**
         * Reset the timer to its initial value
         *
         * Furthermore the stop state will be restored
         * If the countdown is running the countdown value is recalculated. The
         * timer is not stopped in such situation.
         *
         * In presentation mode the time will be reset to the initial
         * presentation time.
         */
static void org_westhoffswelt_pdfpresenter_timer_label_real_reset (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	gint _tmp0_ = 0;
	gint _tmp1_;
	org_westhoffswelt_pdfpresenter_timer_label_stop (self);
	_tmp0_ = org_westhoffswelt_pdfpresenter_timer_label_calculate_countdown (self);
	self->time = _tmp0_;
	_tmp1_ = self->time;
	if (_tmp1_ < 0) {
		org_westhoffswelt_pdfpresenter_timer_label_start (self);
	} else {
		self->time = 0;
	}
	org_westhoffswelt_pdfpresenter_timer_label_format_time (self);
}


void org_westhoffswelt_pdfpresenter_timer_label_reset (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	g_return_if_fail (self != NULL);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_GET_CLASS (self)->reset (self);
}


/**
         * Calculate and return the countdown time in (negative) seconds until
         * the talk begins.
         */
static void g_time_local (time_t time, struct tm* result) {
	struct tm _result_ = {0};
	struct tm _tmp0_ = {0};
	localtime_r (&time, &_tmp0_);
	_result_ = _tmp0_;
	*result = _result_;
	return;
}


gint org_westhoffswelt_pdfpresenter_timer_label_calculate_countdown (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	gint result = 0;
	time_t _tmp0_;
	struct tm _tmp1_ = {0};
	time_t _tmp2_ = 0;
	time_t now;
	time_t _tmp3_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = time (NULL);
	g_time_local (_tmp0_, &_tmp1_);
	_tmp2_ = mktime (&_tmp1_);
	now = _tmp2_;
	_tmp3_ = self->start_time;
	result = (gint) (now - _tmp3_);
	return result;
}


/**
         * Update the timer on every timeout step (every second)
         */
static gboolean org_westhoffswelt_pdfpresenter_timer_label_real_on_timeout (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	gboolean result = FALSE;
	gint _tmp0_;
	_tmp0_ = self->time;
	self->time = _tmp0_ + 1;
	org_westhoffswelt_pdfpresenter_timer_label_format_time (self);
	result = TRUE;
	return result;
}


gboolean org_westhoffswelt_pdfpresenter_timer_label_on_timeout (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_GET_CLASS (self)->on_timeout (self);
}


/**
         * Shows the corresponding time
         */
static void org_westhoffswelt_pdfpresenter_timer_label_real_format_time (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	g_critical ("Type `%s' does not implement abstract method `org_westhoffswelt_pdfpresenter_timer_label_format_time'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void org_westhoffswelt_pdfpresenter_timer_label_format_time (orgwesthoffsweltpdfpresenterTimerLabel* self) {
	g_return_if_fail (self != NULL);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_GET_CLASS (self)->format_time (self);
}


/**
         * Shows a time (in seconds) in hh:mm:ss format, with an additional prefix
         */
void org_westhoffswelt_pdfpresenter_timer_label_show_time (orgwesthoffsweltpdfpresenterTimerLabel* self, guint timeInSecs, const gchar* prefix) {
	guint hours = 0U;
	guint minutes = 0U;
	guint seconds = 0U;
	guint _tmp0_;
	guint _tmp1_;
	guint _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (prefix != NULL);
	_tmp0_ = timeInSecs;
	hours = (_tmp0_ / 60) / 60;
	_tmp1_ = timeInSecs;
	minutes = (_tmp1_ / 60) % 60;
	_tmp2_ = timeInSecs;
	seconds = (_tmp2_ % 60) % 60;
	_tmp3_ = prefix;
	_tmp4_ = g_strdup_printf ("%s%.2u:%.2u:%.2u", _tmp3_, hours, minutes, seconds);
	_tmp5_ = _tmp4_;
	gtk_label_set_text ((GtkLabel*) self, _tmp5_);
	_g_free0 (_tmp5_);
}


static void org_westhoffswelt_pdfpresenter_timer_label_class_init (orgwesthoffsweltpdfpresenterTimerLabelClass * klass) {
	org_westhoffswelt_pdfpresenter_timer_label_parent_class = g_type_class_peek_parent (klass);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->start = org_westhoffswelt_pdfpresenter_timer_label_real_start;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->stop = org_westhoffswelt_pdfpresenter_timer_label_real_stop;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->reset = org_westhoffswelt_pdfpresenter_timer_label_real_reset;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->on_timeout = org_westhoffswelt_pdfpresenter_timer_label_real_on_timeout;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->format_time = org_westhoffswelt_pdfpresenter_timer_label_real_format_time;
	G_OBJECT_CLASS (klass)->finalize = org_westhoffswelt_pdfpresenter_timer_label_finalize;
}


static void org_westhoffswelt_pdfpresenter_timer_label_instance_init (orgwesthoffsweltpdfpresenterTimerLabel * self) {
	self->time = 0;
	self->start_time = (time_t) 0;
	self->timeout = (guint) 0;
}


static void org_westhoffswelt_pdfpresenter_timer_label_finalize (GObject* obj) {
	orgwesthoffsweltpdfpresenterTimerLabel * self;
	self = ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL (obj);
	G_OBJECT_CLASS (org_westhoffswelt_pdfpresenter_timer_label_parent_class)->finalize (obj);
}


/**
     * Specialized label, which is capable of easily displaying a timer
     */
GType org_westhoffswelt_pdfpresenter_timer_label_get_type (void) {
	static volatile gsize org_westhoffswelt_pdfpresenter_timer_label_type_id__volatile = 0;
	if (g_once_init_enter (&org_westhoffswelt_pdfpresenter_timer_label_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (orgwesthoffsweltpdfpresenterTimerLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) org_westhoffswelt_pdfpresenter_timer_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (orgwesthoffsweltpdfpresenterTimerLabel), 0, (GInstanceInitFunc) org_westhoffswelt_pdfpresenter_timer_label_instance_init, NULL };
		GType org_westhoffswelt_pdfpresenter_timer_label_type_id;
		org_westhoffswelt_pdfpresenter_timer_label_type_id = g_type_register_static (GTK_TYPE_LABEL, "orgwesthoffsweltpdfpresenterTimerLabel", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&org_westhoffswelt_pdfpresenter_timer_label_type_id__volatile, org_westhoffswelt_pdfpresenter_timer_label_type_id);
	}
	return org_westhoffswelt_pdfpresenter_timer_label_type_id__volatile;
}


orgwesthoffsweltpdfpresenterCountdownTimer* org_westhoffswelt_pdfpresenter_countdown_timer_construct (GType object_type, gint duration, guint last_minutes, time_t start_time) {
	orgwesthoffsweltpdfpresenterCountdownTimer * self = NULL;
	time_t _tmp0_;
	gint _tmp1_;
	guint _tmp2_;
	GdkColor _tmp3_ = {0};
	GdkColor _tmp4_ = {0};
	_tmp0_ = start_time;
	self = (orgwesthoffsweltpdfpresenterCountdownTimer*) org_westhoffswelt_pdfpresenter_timer_label_construct (object_type, _tmp0_);
	_tmp1_ = duration;
	self->duration = _tmp1_;
	_tmp2_ = last_minutes;
	self->last_minutes = _tmp2_;
	gdk_color_parse ("orange", &_tmp3_);
	self->last_minutes_color = _tmp3_;
	gdk_color_parse ("red", &_tmp4_);
	self->negative_color = _tmp4_;
	return self;
}


orgwesthoffsweltpdfpresenterCountdownTimer* org_westhoffswelt_pdfpresenter_countdown_timer_new (gint duration, guint last_minutes, time_t start_time) {
	return org_westhoffswelt_pdfpresenter_countdown_timer_construct (ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTDOWN_TIMER, duration, last_minutes, start_time);
}


/**
         * Format the given time in a readable hh:mm:ss way and update the
         * label text
         */
static void org_westhoffswelt_pdfpresenter_countdown_timer_real_format_time (orgwesthoffsweltpdfpresenterTimerLabel* base) {
	orgwesthoffsweltpdfpresenterCountdownTimer * self;
	guint timeInSecs = 0U;
	gchar* _tmp0_;
	gchar* prefix;
	gint _tmp1_;
	guint _tmp17_;
	const gchar* _tmp18_;
	self = (orgwesthoffsweltpdfpresenterCountdownTimer*) base;
	_tmp0_ = g_strdup ("");
	prefix = _tmp0_;
	_tmp1_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
	if (_tmp1_ < 0) {
		gchar* _tmp2_;
		gint _tmp3_;
		GdkColor _tmp4_;
		_tmp2_ = g_strdup ("-");
		_g_free0 (prefix);
		prefix = _tmp2_;
		_tmp3_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
		timeInSecs = (guint) (-_tmp3_);
		_tmp4_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->pretalk_color;
		gtk_widget_modify_fg ((GtkWidget*) self, GTK_STATE_NORMAL, &_tmp4_);
	} else {
		gint _tmp5_;
		gint _tmp6_;
		_tmp5_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
		_tmp6_ = self->duration;
		if (_tmp5_ < _tmp6_) {
			gint _tmp7_;
			gint _tmp8_;
			guint _tmp9_;
			guint _tmp10_;
			_tmp7_ = self->duration;
			_tmp8_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
			timeInSecs = (guint) (_tmp7_ - _tmp8_);
			_tmp9_ = timeInSecs;
			_tmp10_ = self->last_minutes;
			if (_tmp9_ < (_tmp10_ * 60)) {
				GdkColor _tmp11_;
				_tmp11_ = self->last_minutes_color;
				gtk_widget_modify_fg ((GtkWidget*) self, GTK_STATE_NORMAL, &_tmp11_);
			} else {
				GdkColor _tmp12_;
				_tmp12_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->normal_color;
				gtk_widget_modify_fg ((GtkWidget*) self, GTK_STATE_NORMAL, &_tmp12_);
			}
		} else {
			GdkColor _tmp13_;
			gint _tmp14_;
			gint _tmp15_;
			gchar* _tmp16_;
			_tmp13_ = self->negative_color;
			gtk_widget_modify_fg ((GtkWidget*) self, GTK_STATE_NORMAL, &_tmp13_);
			_tmp14_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
			_tmp15_ = self->duration;
			timeInSecs = (guint) (_tmp14_ - _tmp15_);
			_tmp16_ = g_strdup ("-");
			_g_free0 (prefix);
			prefix = _tmp16_;
		}
	}
	_tmp17_ = timeInSecs;
	_tmp18_ = prefix;
	org_westhoffswelt_pdfpresenter_timer_label_show_time ((orgwesthoffsweltpdfpresenterTimerLabel*) self, _tmp17_, _tmp18_);
	_g_free0 (prefix);
}


static void org_westhoffswelt_pdfpresenter_countdown_timer_class_init (orgwesthoffsweltpdfpresenterCountdownTimerClass * klass) {
	org_westhoffswelt_pdfpresenter_countdown_timer_parent_class = g_type_class_peek_parent (klass);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->format_time = org_westhoffswelt_pdfpresenter_countdown_timer_real_format_time;
	G_OBJECT_CLASS (klass)->finalize = org_westhoffswelt_pdfpresenter_countdown_timer_finalize;
}


static void org_westhoffswelt_pdfpresenter_countdown_timer_instance_init (orgwesthoffsweltpdfpresenterCountdownTimer * self) {
	self->last_minutes = (guint) 5;
}


static void org_westhoffswelt_pdfpresenter_countdown_timer_finalize (GObject* obj) {
	orgwesthoffsweltpdfpresenterCountdownTimer * self;
	self = ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER (obj);
	G_OBJECT_CLASS (org_westhoffswelt_pdfpresenter_countdown_timer_parent_class)->finalize (obj);
}


GType org_westhoffswelt_pdfpresenter_countdown_timer_get_type (void) {
	static volatile gsize org_westhoffswelt_pdfpresenter_countdown_timer_type_id__volatile = 0;
	if (g_once_init_enter (&org_westhoffswelt_pdfpresenter_countdown_timer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (orgwesthoffsweltpdfpresenterCountdownTimerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) org_westhoffswelt_pdfpresenter_countdown_timer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (orgwesthoffsweltpdfpresenterCountdownTimer), 0, (GInstanceInitFunc) org_westhoffswelt_pdfpresenter_countdown_timer_instance_init, NULL };
		GType org_westhoffswelt_pdfpresenter_countdown_timer_type_id;
		org_westhoffswelt_pdfpresenter_countdown_timer_type_id = g_type_register_static (ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_TIMER_LABEL, "orgwesthoffsweltpdfpresenterCountdownTimer", &g_define_type_info, 0);
		g_once_init_leave (&org_westhoffswelt_pdfpresenter_countdown_timer_type_id__volatile, org_westhoffswelt_pdfpresenter_countdown_timer_type_id);
	}
	return org_westhoffswelt_pdfpresenter_countdown_timer_type_id__volatile;
}


orgwesthoffsweltpdfpresenterEndTimeTimer* org_westhoffswelt_pdfpresenter_end_time_timer_construct (GType object_type, time_t end_time, guint last_minutes, time_t start_time) {
	orgwesthoffsweltpdfpresenterEndTimeTimer * self = NULL;
	guint _tmp0_;
	time_t _tmp1_;
	time_t _tmp2_;
	time_t _tmp3_;
	struct tm _tmp4_ = {0};
	_tmp0_ = last_minutes;
	_tmp1_ = start_time;
	self = (orgwesthoffsweltpdfpresenterEndTimeTimer*) org_westhoffswelt_pdfpresenter_countdown_timer_construct (object_type, 1000, _tmp0_, _tmp1_);
	_tmp2_ = end_time;
	self->end_time = _tmp2_;
	_tmp3_ = end_time;
	g_time_local (_tmp3_, &_tmp4_);
	self->end_time_object = _tmp4_;
	return self;
}


orgwesthoffsweltpdfpresenterEndTimeTimer* org_westhoffswelt_pdfpresenter_end_time_timer_new (time_t end_time, guint last_minutes, time_t start_time) {
	return org_westhoffswelt_pdfpresenter_end_time_timer_construct (ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_END_TIME_TIMER, end_time, last_minutes, start_time);
}


static void org_westhoffswelt_pdfpresenter_end_time_timer_real_start (orgwesthoffsweltpdfpresenterTimerLabel* base) {
	orgwesthoffsweltpdfpresenterEndTimeTimer * self;
	time_t _tmp0_;
	struct tm _tmp1_ = {0};
	time_t _tmp2_ = 0;
	time_t now;
	time_t _tmp3_;
	self = (orgwesthoffsweltpdfpresenterEndTimeTimer*) base;
	_tmp0_ = time (NULL);
	g_time_local (_tmp0_, &_tmp1_);
	_tmp2_ = mktime (&_tmp1_);
	now = _tmp2_;
	_tmp3_ = self->end_time;
	((orgwesthoffsweltpdfpresenterCountdownTimer*) self)->duration = (gint) (_tmp3_ - now);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (org_westhoffswelt_pdfpresenter_end_time_timer_parent_class)->start ((orgwesthoffsweltpdfpresenterTimerLabel*) ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER (self));
}


static gchar* g_time_format (struct tm *self, const gchar* format) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* buffer;
	gint buffer_length1;
	gint _buffer_size_;
	gchar* _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gint _tmp3__length1;
	gchar* _tmp4_;
	g_return_val_if_fail (format != NULL, NULL);
	_tmp0_ = g_new0 (gchar, 64);
	buffer = _tmp0_;
	buffer_length1 = 64;
	_buffer_size_ = buffer_length1;
	_tmp1_ = buffer;
	_tmp1__length1 = buffer_length1;
	_tmp2_ = format;
	strftime (_tmp1_, _tmp1__length1, _tmp2_, &(*self));
	_tmp3_ = buffer;
	_tmp3__length1 = buffer_length1;
	_tmp4_ = g_strdup ((const gchar*) _tmp3_);
	result = _tmp4_;
	buffer = (g_free (buffer), NULL);
	return result;
}


static void org_westhoffswelt_pdfpresenter_end_time_timer_real_stop (orgwesthoffsweltpdfpresenterTimerLabel* base) {
	orgwesthoffsweltpdfpresenterEndTimeTimer * self;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	self = (orgwesthoffsweltpdfpresenterEndTimeTimer*) base;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (org_westhoffswelt_pdfpresenter_end_time_timer_parent_class)->stop ((orgwesthoffsweltpdfpresenterTimerLabel*) ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER (self));
	_tmp0_ = g_time_format (&self->end_time_object, "Until %H:%M");
	_tmp1_ = _tmp0_;
	gtk_label_set_text ((GtkLabel*) self, _tmp1_);
	_g_free0 (_tmp1_);
}


static void org_westhoffswelt_pdfpresenter_end_time_timer_real_reset (orgwesthoffsweltpdfpresenterTimerLabel* base) {
	orgwesthoffsweltpdfpresenterEndTimeTimer * self;
	guint _tmp0_;
	self = (orgwesthoffsweltpdfpresenterEndTimeTimer*) base;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (org_westhoffswelt_pdfpresenter_end_time_timer_parent_class)->reset ((orgwesthoffsweltpdfpresenterTimerLabel*) ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER (self));
	_tmp0_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->timeout;
	if (_tmp0_ == ((guint) 0)) {
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		_tmp1_ = g_time_format (&self->end_time_object, "Until %H:%M");
		_tmp2_ = _tmp1_;
		gtk_label_set_text ((GtkLabel*) self, _tmp2_);
		_g_free0 (_tmp2_);
	}
}


static gboolean org_westhoffswelt_pdfpresenter_end_time_timer_real_on_timeout (orgwesthoffsweltpdfpresenterTimerLabel* base) {
	orgwesthoffsweltpdfpresenterEndTimeTimer * self;
	gboolean result = FALSE;
	gint _tmp0_;
	gboolean _tmp6_ = FALSE;
	self = (orgwesthoffsweltpdfpresenterEndTimeTimer*) base;
	_tmp0_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
	if (_tmp0_ == (-1)) {
		time_t _tmp1_;
		struct tm _tmp2_ = {0};
		time_t _tmp3_ = 0;
		time_t now;
		time_t _tmp4_;
		time_t _tmp5_;
		_tmp1_ = time (NULL);
		g_time_local (_tmp1_, &_tmp2_);
		_tmp3_ = mktime (&_tmp2_);
		now = _tmp3_;
		_tmp4_ = self->end_time;
		_tmp5_ = now;
		((orgwesthoffsweltpdfpresenterCountdownTimer*) self)->duration = (gint) (_tmp4_ - _tmp5_);
	}
	_tmp6_ = ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (org_westhoffswelt_pdfpresenter_end_time_timer_parent_class)->on_timeout ((orgwesthoffsweltpdfpresenterTimerLabel*) ORG_WESTHOFFSWELT_PDFPRESENTER_COUNTDOWN_TIMER (self));
	result = _tmp6_;
	return result;
}


static void org_westhoffswelt_pdfpresenter_end_time_timer_class_init (orgwesthoffsweltpdfpresenterEndTimeTimerClass * klass) {
	org_westhoffswelt_pdfpresenter_end_time_timer_parent_class = g_type_class_peek_parent (klass);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->start = org_westhoffswelt_pdfpresenter_end_time_timer_real_start;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->stop = org_westhoffswelt_pdfpresenter_end_time_timer_real_stop;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->reset = org_westhoffswelt_pdfpresenter_end_time_timer_real_reset;
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->on_timeout = org_westhoffswelt_pdfpresenter_end_time_timer_real_on_timeout;
	G_OBJECT_CLASS (klass)->finalize = org_westhoffswelt_pdfpresenter_end_time_timer_finalize;
}


static void org_westhoffswelt_pdfpresenter_end_time_timer_instance_init (orgwesthoffsweltpdfpresenterEndTimeTimer * self) {
}


static void org_westhoffswelt_pdfpresenter_end_time_timer_finalize (GObject* obj) {
	orgwesthoffsweltpdfpresenterEndTimeTimer * self;
	self = ORG_WESTHOFFSWELT_PDFPRESENTER_END_TIME_TIMER (obj);
	G_OBJECT_CLASS (org_westhoffswelt_pdfpresenter_end_time_timer_parent_class)->finalize (obj);
}


GType org_westhoffswelt_pdfpresenter_end_time_timer_get_type (void) {
	static volatile gsize org_westhoffswelt_pdfpresenter_end_time_timer_type_id__volatile = 0;
	if (g_once_init_enter (&org_westhoffswelt_pdfpresenter_end_time_timer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (orgwesthoffsweltpdfpresenterEndTimeTimerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) org_westhoffswelt_pdfpresenter_end_time_timer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (orgwesthoffsweltpdfpresenterEndTimeTimer), 0, (GInstanceInitFunc) org_westhoffswelt_pdfpresenter_end_time_timer_instance_init, NULL };
		GType org_westhoffswelt_pdfpresenter_end_time_timer_type_id;
		org_westhoffswelt_pdfpresenter_end_time_timer_type_id = g_type_register_static (ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTDOWN_TIMER, "orgwesthoffsweltpdfpresenterEndTimeTimer", &g_define_type_info, 0);
		g_once_init_leave (&org_westhoffswelt_pdfpresenter_end_time_timer_type_id__volatile, org_westhoffswelt_pdfpresenter_end_time_timer_type_id);
	}
	return org_westhoffswelt_pdfpresenter_end_time_timer_type_id__volatile;
}


orgwesthoffsweltpdfpresenterCountupTimer* org_westhoffswelt_pdfpresenter_countup_timer_construct (GType object_type, time_t start_time) {
	orgwesthoffsweltpdfpresenterCountupTimer * self = NULL;
	time_t _tmp0_;
	_tmp0_ = start_time;
	self = (orgwesthoffsweltpdfpresenterCountupTimer*) org_westhoffswelt_pdfpresenter_timer_label_construct (object_type, _tmp0_);
	return self;
}


orgwesthoffsweltpdfpresenterCountupTimer* org_westhoffswelt_pdfpresenter_countup_timer_new (time_t start_time) {
	return org_westhoffswelt_pdfpresenter_countup_timer_construct (ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_COUNTUP_TIMER, start_time);
}


/**
         * Format the given time in a readable hh:mm:ss way and update the
         * label text
         */
static void org_westhoffswelt_pdfpresenter_countup_timer_real_format_time (orgwesthoffsweltpdfpresenterTimerLabel* base) {
	orgwesthoffsweltpdfpresenterCountupTimer * self;
	guint timeInSecs = 0U;
	gchar* _tmp0_;
	gchar* prefix;
	gint _tmp1_;
	guint _tmp7_;
	const gchar* _tmp8_;
	self = (orgwesthoffsweltpdfpresenterCountupTimer*) base;
	_tmp0_ = g_strdup ("");
	prefix = _tmp0_;
	_tmp1_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
	if (_tmp1_ < 0) {
		gchar* _tmp2_;
		gint _tmp3_;
		GdkColor _tmp4_;
		_tmp2_ = g_strdup ("-");
		_g_free0 (prefix);
		prefix = _tmp2_;
		_tmp3_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
		timeInSecs = (guint) (-_tmp3_);
		_tmp4_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->pretalk_color;
		gtk_widget_modify_fg ((GtkWidget*) self, GTK_STATE_NORMAL, &_tmp4_);
	} else {
		gint _tmp5_;
		GdkColor _tmp6_;
		_tmp5_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->time;
		timeInSecs = (guint) _tmp5_;
		_tmp6_ = ((orgwesthoffsweltpdfpresenterTimerLabel*) self)->normal_color;
		gtk_widget_modify_fg ((GtkWidget*) self, GTK_STATE_NORMAL, &_tmp6_);
	}
	_tmp7_ = timeInSecs;
	_tmp8_ = prefix;
	org_westhoffswelt_pdfpresenter_timer_label_show_time ((orgwesthoffsweltpdfpresenterTimerLabel*) self, _tmp7_, _tmp8_);
	_g_free0 (prefix);
}


static void org_westhoffswelt_pdfpresenter_countup_timer_class_init (orgwesthoffsweltpdfpresenterCountupTimerClass * klass) {
	org_westhoffswelt_pdfpresenter_countup_timer_parent_class = g_type_class_peek_parent (klass);
	ORG_WESTHOFFSWELT_PDFPRESENTER_TIMER_LABEL_CLASS (klass)->format_time = org_westhoffswelt_pdfpresenter_countup_timer_real_format_time;
}


static void org_westhoffswelt_pdfpresenter_countup_timer_instance_init (orgwesthoffsweltpdfpresenterCountupTimer * self) {
}


GType org_westhoffswelt_pdfpresenter_countup_timer_get_type (void) {
	static volatile gsize org_westhoffswelt_pdfpresenter_countup_timer_type_id__volatile = 0;
	if (g_once_init_enter (&org_westhoffswelt_pdfpresenter_countup_timer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (orgwesthoffsweltpdfpresenterCountupTimerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) org_westhoffswelt_pdfpresenter_countup_timer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (orgwesthoffsweltpdfpresenterCountupTimer), 0, (GInstanceInitFunc) org_westhoffswelt_pdfpresenter_countup_timer_instance_init, NULL };
		GType org_westhoffswelt_pdfpresenter_countup_timer_type_id;
		org_westhoffswelt_pdfpresenter_countup_timer_type_id = g_type_register_static (ORG_WESTHOFFSWELT_PDFPRESENTER_TYPE_TIMER_LABEL, "orgwesthoffsweltpdfpresenterCountupTimer", &g_define_type_info, 0);
		g_once_init_leave (&org_westhoffswelt_pdfpresenter_countup_timer_type_id__volatile, org_westhoffswelt_pdfpresenter_countup_timer_type_id);
	}
	return org_westhoffswelt_pdfpresenter_countup_timer_type_id__volatile;
}



