/* prerendering.c generated by valac 0.16.0, the Vala compiler
 * generated from prerendering.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_PRERENDERING (org_westhoffswelt_pdfpresenter_view_prerendering_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_PRERENDERING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_PRERENDERING, orgwesthoffsweltpdfpresenterViewPrerendering))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_IS_PRERENDERING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_PRERENDERING))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_PRERENDERING_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_PRERENDERING, orgwesthoffsweltpdfpresenterViewPrerenderingIface))

typedef struct _orgwesthoffsweltpdfpresenterViewPrerendering orgwesthoffsweltpdfpresenterViewPrerendering;
typedef struct _orgwesthoffsweltpdfpresenterViewPrerenderingIface orgwesthoffsweltpdfpresenterViewPrerenderingIface;

struct _orgwesthoffsweltpdfpresenterViewPrerenderingIface {
	GTypeInterface parent_iface;
};



GType org_westhoffswelt_pdfpresenter_view_prerendering_get_type (void) G_GNUC_CONST;


static void org_westhoffswelt_pdfpresenter_view_prerendering_base_init (orgwesthoffsweltpdfpresenterViewPrerenderingIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		/**
		         * Signal emitted every time a precached slide has been created
		         *
		         * This signal should be emitted slide_count number of times during a
		         * precaching cylce.
		         */
		g_signal_new ("slide_prerendered", ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_PRERENDERING, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
		/**
		         * Signal emitted when the precaching cycle is complete
		         */
		g_signal_new ("prerendering_completed", ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_PRERENDERING, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
		/**
		         * Signal emitted when the precaching cycle just started
		         */
		g_signal_new ("prerendering_started", ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_PRERENDERING, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	}
}


/**
     * Every View may implement this interface to allow prerendering of slides
     * for display speed improvements. If however a renderer is used with the
     * view, which does not implement the Renderer.Caching interface the
     * prerender functionallity can't be used.
     */
GType org_westhoffswelt_pdfpresenter_view_prerendering_get_type (void) {
	static volatile gsize org_westhoffswelt_pdfpresenter_view_prerendering_type_id__volatile = 0;
	if (g_once_init_enter (&org_westhoffswelt_pdfpresenter_view_prerendering_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (orgwesthoffsweltpdfpresenterViewPrerenderingIface), (GBaseInitFunc) org_westhoffswelt_pdfpresenter_view_prerendering_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType org_westhoffswelt_pdfpresenter_view_prerendering_type_id;
		org_westhoffswelt_pdfpresenter_view_prerendering_type_id = g_type_register_static (G_TYPE_INTERFACE, "orgwesthoffsweltpdfpresenterViewPrerendering", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (org_westhoffswelt_pdfpresenter_view_prerendering_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&org_westhoffswelt_pdfpresenter_view_prerendering_type_id__volatile, org_westhoffswelt_pdfpresenter_view_prerendering_type_id);
	}
	return org_westhoffswelt_pdfpresenter_view_prerendering_type_id__volatile;
}



