/* base.c generated by valac 0.16.0, the Vala compiler
 * generated from base.vala, do not modify */

/**
         * Goto the next slide
         *
         * If the end of slides is reached this method is expected to do
         * nothing.
         */
/**
         * Go forward 10 slides
         *
         * If the end of slides is reached this method is expected to do
         * nothing.
         */
/**
         * Goto the previous slide
         *
         * If the beginning of slides is reached this method is expected to do
         * nothing.
         */
/**
         * Go back 10 slides
         *
         * If the beginning of slides is reached this method does nothing.
         */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE (org_westhoffswelt_pdfpresenter_view_base_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBase))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBaseClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_IS_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_IS_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBaseClass))

typedef struct _orgwesthoffsweltpdfpresenterViewBase orgwesthoffsweltpdfpresenterViewBase;
typedef struct _orgwesthoffsweltpdfpresenterViewBaseClass orgwesthoffsweltpdfpresenterViewBaseClass;
typedef struct _orgwesthoffsweltpdfpresenterViewBasePrivate orgwesthoffsweltpdfpresenterViewBasePrivate;

#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_TYPE_BASE (org_westhoffswelt_pdfpresenter_renderer_base_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_TYPE_BASE, orgwesthoffsweltpdfpresenterRendererBase))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_TYPE_BASE, orgwesthoffsweltpdfpresenterRendererBaseClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_IS_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_IS_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_TYPE_BASE, orgwesthoffsweltpdfpresenterRendererBaseClass))

typedef struct _orgwesthoffsweltpdfpresenterRendererBase orgwesthoffsweltpdfpresenterRendererBase;
typedef struct _orgwesthoffsweltpdfpresenterRendererBaseClass orgwesthoffsweltpdfpresenterRendererBaseClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

typedef enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_RENDER_ERROR_SLIDE_DOES_NOT_EXIST
} orgwesthoffsweltpdfpresenterRendererRenderError;
#define ORG_WESTHOFFSWELT_PDFPRESENTER_RENDERER_RENDER_ERROR org_westhoffswelt_pdfpresenter_renderer_render_error_quark ()
struct _orgwesthoffsweltpdfpresenterViewBase {
	GtkDrawingArea parent_instance;
	orgwesthoffsweltpdfpresenterViewBasePrivate * priv;
	orgwesthoffsweltpdfpresenterRendererBase* renderer;
};

struct _orgwesthoffsweltpdfpresenterViewBaseClass {
	GtkDrawingAreaClass parent_class;
	void (*display) (orgwesthoffsweltpdfpresenterViewBase* self, gint slide_number, gboolean force_redraw, GError** error);
	void (*fade_to_black) (orgwesthoffsweltpdfpresenterViewBase* self);
	void (*redraw) (orgwesthoffsweltpdfpresenterViewBase* self, GError** error);
	gint (*get_current_slide_number) (orgwesthoffsweltpdfpresenterViewBase* self);
};


static gpointer org_westhoffswelt_pdfpresenter_view_base_parent_class = NULL;

GType org_westhoffswelt_pdfpresenter_view_base_get_type (void) G_GNUC_CONST;
GQuark org_westhoffswelt_pdfpresenter_renderer_render_error_quark (void);
GType org_westhoffswelt_pdfpresenter_renderer_base_get_type (void) G_GNUC_CONST;
enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_DUMMY_PROPERTY
};
orgwesthoffsweltpdfpresenterViewBase* org_westhoffswelt_pdfpresenter_view_base_construct (GType object_type, orgwesthoffsweltpdfpresenterRendererBase* renderer);
gint org_westhoffswelt_pdfpresenter_renderer_base_get_width (orgwesthoffsweltpdfpresenterRendererBase* self);
gint org_westhoffswelt_pdfpresenter_renderer_base_get_height (orgwesthoffsweltpdfpresenterRendererBase* self);
orgwesthoffsweltpdfpresenterRendererBase* org_westhoffswelt_pdfpresenter_view_base_get_renderer (orgwesthoffsweltpdfpresenterViewBase* self);
void org_westhoffswelt_pdfpresenter_view_base_display (orgwesthoffsweltpdfpresenterViewBase* self, gint slide_number, gboolean force_redraw, GError** error);
static void org_westhoffswelt_pdfpresenter_view_base_real_display (orgwesthoffsweltpdfpresenterViewBase* self, gint slide_number, gboolean force_redraw, GError** error);
void org_westhoffswelt_pdfpresenter_view_base_fade_to_black (orgwesthoffsweltpdfpresenterViewBase* self);
static void org_westhoffswelt_pdfpresenter_view_base_real_fade_to_black (orgwesthoffsweltpdfpresenterViewBase* self);
void org_westhoffswelt_pdfpresenter_view_base_redraw (orgwesthoffsweltpdfpresenterViewBase* self, GError** error);
static void org_westhoffswelt_pdfpresenter_view_base_real_redraw (orgwesthoffsweltpdfpresenterViewBase* self, GError** error);
gint org_westhoffswelt_pdfpresenter_view_base_get_current_slide_number (orgwesthoffsweltpdfpresenterViewBase* self);
static gint org_westhoffswelt_pdfpresenter_view_base_real_get_current_slide_number (orgwesthoffsweltpdfpresenterViewBase* self);
static void g_cclosure_user_marshal_VOID__INT_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void org_westhoffswelt_pdfpresenter_view_base_finalize (GObject* obj);


/**
         * Base constructor taking the renderer to use as an argument
         */
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


orgwesthoffsweltpdfpresenterViewBase* org_westhoffswelt_pdfpresenter_view_base_construct (GType object_type, orgwesthoffsweltpdfpresenterRendererBase* renderer) {
	orgwesthoffsweltpdfpresenterViewBase * self = NULL;
	orgwesthoffsweltpdfpresenterRendererBase* _tmp0_;
	orgwesthoffsweltpdfpresenterRendererBase* _tmp1_;
	orgwesthoffsweltpdfpresenterRendererBase* _tmp2_;
	gint _tmp3_ = 0;
	orgwesthoffsweltpdfpresenterRendererBase* _tmp4_;
	gint _tmp5_ = 0;
	g_return_val_if_fail (renderer != NULL, NULL);
	self = (orgwesthoffsweltpdfpresenterViewBase*) g_object_new (object_type, NULL);
	_tmp0_ = renderer;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->renderer);
	self->renderer = _tmp1_;
	_tmp2_ = renderer;
	_tmp3_ = org_westhoffswelt_pdfpresenter_renderer_base_get_width (_tmp2_);
	_tmp4_ = renderer;
	_tmp5_ = org_westhoffswelt_pdfpresenter_renderer_base_get_height (_tmp4_);
	gtk_widget_set_size_request ((GtkWidget*) self, _tmp3_, _tmp5_);
	return self;
}


/**
         * Return the used renderer object
         */
orgwesthoffsweltpdfpresenterRendererBase* org_westhoffswelt_pdfpresenter_view_base_get_renderer (orgwesthoffsweltpdfpresenterViewBase* self) {
	orgwesthoffsweltpdfpresenterRendererBase* result = NULL;
	orgwesthoffsweltpdfpresenterRendererBase* _tmp0_;
	orgwesthoffsweltpdfpresenterRendererBase* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->renderer;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


/**
         * Goto a specific slide number
         *
         * If the slide number does not exist a RenderError.SLIDE_DOES_NOT_EXIST is thrown
         */
static void org_westhoffswelt_pdfpresenter_view_base_real_display (orgwesthoffsweltpdfpresenterViewBase* self, gint slide_number, gboolean force_redraw, GError** error) {
	g_critical ("Type `%s' does not implement abstract method `org_westhoffswelt_pdfpresenter_view_base_display'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void org_westhoffswelt_pdfpresenter_view_base_display (orgwesthoffsweltpdfpresenterViewBase* self, gint slide_number, gboolean force_redraw, GError** error) {
	g_return_if_fail (self != NULL);
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_GET_CLASS (self)->display (self, slide_number, force_redraw, error);
}


/**
         * Make the screen black. Useful for presentations together with a whiteboard
         */
static void org_westhoffswelt_pdfpresenter_view_base_real_fade_to_black (orgwesthoffsweltpdfpresenterViewBase* self) {
	g_critical ("Type `%s' does not implement abstract method `org_westhoffswelt_pdfpresenter_view_base_fade_to_black'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void org_westhoffswelt_pdfpresenter_view_base_fade_to_black (orgwesthoffsweltpdfpresenterViewBase* self) {
	g_return_if_fail (self != NULL);
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_GET_CLASS (self)->fade_to_black (self);
}


/**
         * Redraw the current slide. Useful for example when exiting from fade_to_black
         */
static void org_westhoffswelt_pdfpresenter_view_base_real_redraw (orgwesthoffsweltpdfpresenterViewBase* self, GError** error) {
	g_critical ("Type `%s' does not implement abstract method `org_westhoffswelt_pdfpresenter_view_base_redraw'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void org_westhoffswelt_pdfpresenter_view_base_redraw (orgwesthoffsweltpdfpresenterViewBase* self, GError** error) {
	g_return_if_fail (self != NULL);
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_GET_CLASS (self)->redraw (self, error);
}


/**
         * Return the currently shown slide number
         */
static gint org_westhoffswelt_pdfpresenter_view_base_real_get_current_slide_number (orgwesthoffsweltpdfpresenterViewBase* self) {
	g_critical ("Type `%s' does not implement abstract method `org_westhoffswelt_pdfpresenter_view_base_get_current_slide_number'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return 0;
}


gint org_westhoffswelt_pdfpresenter_view_base_get_current_slide_number (orgwesthoffsweltpdfpresenterViewBase* self) {
	g_return_val_if_fail (self != NULL, 0);
	return ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_GET_CLASS (self)->get_current_slide_number (self);
}


static void g_cclosure_user_marshal_VOID__INT_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__INT_INT) (gpointer data1, gint arg_1, gint arg_2, gpointer data2);
	register GMarshalFunc_VOID__INT_INT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__INT_INT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_int (param_values + 1), g_value_get_int (param_values + 2), data2);
}


static void org_westhoffswelt_pdfpresenter_view_base_class_init (orgwesthoffsweltpdfpresenterViewBaseClass * klass) {
	org_westhoffswelt_pdfpresenter_view_base_parent_class = g_type_class_peek_parent (klass);
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_CLASS (klass)->display = org_westhoffswelt_pdfpresenter_view_base_real_display;
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_CLASS (klass)->fade_to_black = org_westhoffswelt_pdfpresenter_view_base_real_fade_to_black;
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_CLASS (klass)->redraw = org_westhoffswelt_pdfpresenter_view_base_real_redraw;
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_CLASS (klass)->get_current_slide_number = org_westhoffswelt_pdfpresenter_view_base_real_get_current_slide_number;
	G_OBJECT_CLASS (klass)->finalize = org_westhoffswelt_pdfpresenter_view_base_finalize;
	/**
	         * Signal fired every time a slide is about to be left
	         */
	g_signal_new ("leaving_slide", ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__INT_INT, G_TYPE_NONE, 2, G_TYPE_INT, G_TYPE_INT);
	/**
	         * Signal fired every time a slide is entered
	         */
	g_signal_new ("entering_slide", ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
}


static void org_westhoffswelt_pdfpresenter_view_base_instance_init (orgwesthoffsweltpdfpresenterViewBase * self) {
}


static void org_westhoffswelt_pdfpresenter_view_base_finalize (GObject* obj) {
	orgwesthoffsweltpdfpresenterViewBase * self;
	self = ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE (obj);
	_g_object_unref0 (self->renderer);
	G_OBJECT_CLASS (org_westhoffswelt_pdfpresenter_view_base_parent_class)->finalize (obj);
}


/**
     * Base class for every slide view
     */
GType org_westhoffswelt_pdfpresenter_view_base_get_type (void) {
	static volatile gsize org_westhoffswelt_pdfpresenter_view_base_type_id__volatile = 0;
	if (g_once_init_enter (&org_westhoffswelt_pdfpresenter_view_base_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (orgwesthoffsweltpdfpresenterViewBaseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) org_westhoffswelt_pdfpresenter_view_base_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (orgwesthoffsweltpdfpresenterViewBase), 0, (GInstanceInitFunc) org_westhoffswelt_pdfpresenter_view_base_instance_init, NULL };
		GType org_westhoffswelt_pdfpresenter_view_base_type_id;
		org_westhoffswelt_pdfpresenter_view_base_type_id = g_type_register_static (GTK_TYPE_DRAWING_AREA, "orgwesthoffsweltpdfpresenterViewBase", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&org_westhoffswelt_pdfpresenter_view_base_type_id__volatile, org_westhoffswelt_pdfpresenter_view_base_type_id);
	}
	return org_westhoffswelt_pdfpresenter_view_base_type_id__volatile;
}



