pdf_presenter_console: pdf_presenter_console.vala pdf_image.vala presentation_window.vala presentation_controller.vala presenter_window.vala
	valac --thread --pkg gio-2.0 --pkg poppler-glib --pkg gtk+-2.0 --pkg posix -o pdf_presenter_console pdf_presenter_console.vala pdf_image.vala presentation_window.vala presentation_controller.vala presenter_window.vala
