/* base.c generated by valac 0.16.0, the Vala compiler
 * generated from base.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_TYPE_BASE (org_westhoffswelt_pdfpresenter_view_behaviour_base_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBehaviourBase))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBehaviourBaseClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_IS_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_IS_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBehaviourBaseClass))

typedef struct _orgwesthoffsweltpdfpresenterViewBehaviourBase orgwesthoffsweltpdfpresenterViewBehaviourBase;
typedef struct _orgwesthoffsweltpdfpresenterViewBehaviourBaseClass orgwesthoffsweltpdfpresenterViewBehaviourBaseClass;
typedef struct _orgwesthoffsweltpdfpresenterViewBehaviourBasePrivate orgwesthoffsweltpdfpresenterViewBehaviourBasePrivate;

#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE (org_westhoffswelt_pdfpresenter_view_base_get_type ())
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBase))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBaseClass))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_IS_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_IS_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE))
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_TYPE_BASE, orgwesthoffsweltpdfpresenterViewBaseClass))

typedef struct _orgwesthoffsweltpdfpresenterViewBase orgwesthoffsweltpdfpresenterViewBase;
typedef struct _orgwesthoffsweltpdfpresenterViewBaseClass orgwesthoffsweltpdfpresenterViewBaseClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

typedef enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR_BEHAVIOUR_ALREADY_ASSOCIATED,
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR_VIEW_NOT_SUPPORTED
} orgwesthoffsweltpdfpresenterViewBehaviourAssociationError;
#define ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR org_westhoffswelt_pdfpresenter_view_behaviour_association_error_quark ()
struct _orgwesthoffsweltpdfpresenterViewBehaviourBase {
	GObject parent_instance;
	orgwesthoffsweltpdfpresenterViewBehaviourBasePrivate * priv;
	orgwesthoffsweltpdfpresenterViewBase* target;
};

struct _orgwesthoffsweltpdfpresenterViewBehaviourBaseClass {
	GObjectClass parent_class;
	void (*associate) (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target, GError** error);
};

/**
     * Error domain used for association errors
     */

static gpointer org_westhoffswelt_pdfpresenter_view_behaviour_base_parent_class = NULL;

GType org_westhoffswelt_pdfpresenter_view_behaviour_base_get_type (void) G_GNUC_CONST;
GType org_westhoffswelt_pdfpresenter_view_base_get_type (void) G_GNUC_CONST;
GQuark org_westhoffswelt_pdfpresenter_view_behaviour_association_error_quark (void);
enum  {
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_BASE_DUMMY_PROPERTY
};
orgwesthoffsweltpdfpresenterViewBehaviourBase* org_westhoffswelt_pdfpresenter_view_behaviour_base_construct (GType object_type);
orgwesthoffsweltpdfpresenterViewBase* org_westhoffswelt_pdfpresenter_view_behaviour_base_get_target (orgwesthoffsweltpdfpresenterViewBehaviourBase* self);
void org_westhoffswelt_pdfpresenter_view_behaviour_base_enforce_exclusive_association (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target, GError** error);
gboolean org_westhoffswelt_pdfpresenter_view_behaviour_base_is_supported (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target);
void org_westhoffswelt_pdfpresenter_view_behaviour_base_associate (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target, GError** error);
static void org_westhoffswelt_pdfpresenter_view_behaviour_base_real_associate (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target, GError** error);
static void org_westhoffswelt_pdfpresenter_view_behaviour_base_finalize (GObject* obj);


/**
         * Base constructor not taking any arguments
         */
orgwesthoffsweltpdfpresenterViewBehaviourBase* org_westhoffswelt_pdfpresenter_view_behaviour_base_construct (GType object_type) {
	orgwesthoffsweltpdfpresenterViewBehaviourBase * self = NULL;
	self = (orgwesthoffsweltpdfpresenterViewBehaviourBase*) g_object_new (object_type, NULL);
	return self;
}


/**
         * Return the associated View object
         *
         * If no View has been associated yet null is returned
         */
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


orgwesthoffsweltpdfpresenterViewBase* org_westhoffswelt_pdfpresenter_view_behaviour_base_get_target (orgwesthoffsweltpdfpresenterViewBehaviourBase* self) {
	orgwesthoffsweltpdfpresenterViewBase* result = NULL;
	orgwesthoffsweltpdfpresenterViewBase* _tmp0_;
	orgwesthoffsweltpdfpresenterViewBase* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->target;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


/**
         * Enfore the fact that a Behaviour may only be associated to one View
         */
void org_westhoffswelt_pdfpresenter_view_behaviour_base_enforce_exclusive_association (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target, GError** error) {
	orgwesthoffsweltpdfpresenterViewBase* _tmp0_;
	orgwesthoffsweltpdfpresenterViewBase* _tmp1_;
	orgwesthoffsweltpdfpresenterViewBase* _tmp2_;
	orgwesthoffsweltpdfpresenterViewBase* _tmp4_;
	gboolean _tmp5_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (target != NULL);
	_tmp0_ = self->target;
	_tmp1_ = target;
	if (_tmp0_ == _tmp1_) {
		return;
	}
	_tmp2_ = self->target;
	if (_tmp2_ != NULL) {
		GError* _tmp3_;
		_tmp3_ = g_error_new_literal (ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR, ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR_BEHAVIOUR_ALREADY_ASSOCIATED, "A behaviour has been associated with two different Views.");
		_inner_error_ = _tmp3_;
		if (_inner_error_->domain == ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_tmp4_ = target;
	_tmp5_ = org_westhoffswelt_pdfpresenter_view_behaviour_base_is_supported (self, _tmp4_);
	if (!_tmp5_) {
		GError* _tmp6_;
		_tmp6_ = g_error_new_literal (ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR, ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR_VIEW_NOT_SUPPORTED, "The View which should be associated is incompatible to the given Behav" \
"iour");
		_inner_error_ = _tmp6_;
		if (_inner_error_->domain == ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_ASSOCIATION_ERROR) {
			g_propagate_error (error, _inner_error_);
			return;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
}


/**
         * Associate the implementing Behaviour with the given View
         */
static void org_westhoffswelt_pdfpresenter_view_behaviour_base_real_associate (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target, GError** error) {
	g_critical ("Type `%s' does not implement abstract method `org_westhoffswelt_pdfpresenter_view_behaviour_base_associate'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
	return;
}


void org_westhoffswelt_pdfpresenter_view_behaviour_base_associate (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target, GError** error) {
	g_return_if_fail (self != NULL);
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_BASE_GET_CLASS (self)->associate (self, target, error);
}


/**
         * Check wheter the given target is supported by this Behaviour
         *
         * By default every View is supported.
         */
gboolean org_westhoffswelt_pdfpresenter_view_behaviour_base_is_supported (orgwesthoffsweltpdfpresenterViewBehaviourBase* self, orgwesthoffsweltpdfpresenterViewBase* target) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (target != NULL, FALSE);
	result = TRUE;
	return result;
}


static void org_westhoffswelt_pdfpresenter_view_behaviour_base_class_init (orgwesthoffsweltpdfpresenterViewBehaviourBaseClass * klass) {
	org_westhoffswelt_pdfpresenter_view_behaviour_base_parent_class = g_type_class_peek_parent (klass);
	ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_BASE_CLASS (klass)->associate = org_westhoffswelt_pdfpresenter_view_behaviour_base_real_associate;
	G_OBJECT_CLASS (klass)->finalize = org_westhoffswelt_pdfpresenter_view_behaviour_base_finalize;
}


static void org_westhoffswelt_pdfpresenter_view_behaviour_base_instance_init (orgwesthoffsweltpdfpresenterViewBehaviourBase * self) {
	self->target = NULL;
}


static void org_westhoffswelt_pdfpresenter_view_behaviour_base_finalize (GObject* obj) {
	orgwesthoffsweltpdfpresenterViewBehaviourBase * self;
	self = ORG_WESTHOFFSWELT_PDFPRESENTER_VIEW_BEHAVIOUR_BASE (obj);
	_g_object_unref0 (self->target);
	G_OBJECT_CLASS (org_westhoffswelt_pdfpresenter_view_behaviour_base_parent_class)->finalize (obj);
}


/**
     * Abstract base every View Behaviour implementation has to extend.
     *
     * A Behaviour is a certain characteristic which is added to an existing
     * View on demand.
     */
GType org_westhoffswelt_pdfpresenter_view_behaviour_base_get_type (void) {
	static volatile gsize org_westhoffswelt_pdfpresenter_view_behaviour_base_type_id__volatile = 0;
	if (g_once_init_enter (&org_westhoffswelt_pdfpresenter_view_behaviour_base_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (orgwesthoffsweltpdfpresenterViewBehaviourBaseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) org_westhoffswelt_pdfpresenter_view_behaviour_base_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (orgwesthoffsweltpdfpresenterViewBehaviourBase), 0, (GInstanceInitFunc) org_westhoffswelt_pdfpresenter_view_behaviour_base_instance_init, NULL };
		GType org_westhoffswelt_pdfpresenter_view_behaviour_base_type_id;
		org_westhoffswelt_pdfpresenter_view_behaviour_base_type_id = g_type_register_static (G_TYPE_OBJECT, "orgwesthoffsweltpdfpresenterViewBehaviourBase", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&org_westhoffswelt_pdfpresenter_view_behaviour_base_type_id__volatile, org_westhoffswelt_pdfpresenter_view_behaviour_base_type_id);
	}
	return org_westhoffswelt_pdfpresenter_view_behaviour_base_type_id__volatile;
}


GQuark org_westhoffswelt_pdfpresenter_view_behaviour_association_error_quark (void) {
	return g_quark_from_static_string ("org_westhoffswelt_pdfpresenter_view_behaviour_association_error-quark");
}



